### ISSUE TITLE
error at index page

### ISSUE THREAD

**Issue by moeinrahimi** [mikeal/roll-call#32]
hi below error appears on index page :
````
Error: Cannot find module 'filestream/write' from 'C:\Users\KingSlayer\Desktop\roll-call-master'
    at C:\Users\KingSlayer\Desktop\roll-call-master\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\KingSlayer\Desktop\roll-call-master\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\KingSlayer\Desktop\roll-call-master\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\KingSlayer\Desktop\roll-call-master\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\KingSlayer\Desktop\roll-call-master\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\KingSlayer\Desktop\roll-call-master\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

````

**Comment by mikeal** [comment]
Oh wow, the package.json is way out of date, I'll go in and fix it.

**Comment by mikeal** [comment]
Fixed :) https://github.com/mikeal/roll-call/commit/5643e3842c96708da0f1cf0014e45ff67e3375e7
